version: "3.7"
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - api
    networks:
      - cpa-network
  api:
    image: joaopedrogama/cpa-api
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    environment:
        SPRING_PROFILES_ACTIVE: docker
    networks:
      - cpa-network
  mysql_db:
    image: "mysql:8.0"
    container_name: mysql_cpa_front
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - cpa-network
      

networks:
  cpa-network:
    driver: bridge
